name: deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/deploy-test' || github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          pip3 install -r jenkins-requirements.txt
          python3 ./freeze_web.py

      - name: push to build branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git checkout -B build 
          git add app/build
          git commit -m "ci: update build artifacts" || echo "Nothing to commit"
          git push origin build --force
